### ISSUE TITLE
Dataset in CoronaWhy Dataverse

### ISSUE THREAD

**Issue by geek80** [Melykuti/COVID-19#3]
Hello,Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe https://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/OZPD0N

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by Melykuti** [comment]
I am pleased that you did. The datasets are population sizes for countries, for federal states of Germany and for administrative districts of Baden-Württemberg. I do not own or update them and their sources are clearly marked on these pages. Due to capacity constraints, I do not volunteer to maintain them on the page that you linked. I appreciate your understanding.

**Comment by geek80** [comment]
Thank you.
